= Couchbase Tutorials
:page-layout: tutorials
:page-role: tiles
:!sectids:

[.developer]
== Mobile Developer

[.title]
=== xref:tutorials:mobile-travel-sample:introduction.adoc[Travel Sample Mobile]

[.content]

[.summary]
An in-depth tutorial that demonstrates key end-to-end Couchbase Mobile 2.0 capabilities for iOS, Android and .NET (UWP and Xamarin) platforms. The Travel Sample app will allow users to search for and to make flight reservations Shared bucket access is enabled to allow web and mobile clients to perform the same operations on the bucket.
[.links]
xref:tutorials:mobile-travel-sample:swift/design/data-modeling.adoc[iOS]
xref:tutorials:mobile-travel-sample:java/design/data-modeling.adoc[Java]

===== {empty}

====== Components
* Server 5.5
* Lite 2.1
* Sync Gateway 2.1

====== Languages
* Swift
* Java
* C#

[.metadata]
=== Intermediate

[.developer]
== Developer

[.title]
=== xref:tutorials:session-storage:aspnet.adoc[Using Couchbase Server as a Session Store]

[.content]

[.summary]
An in-depth tutorial that demonstrates how to use Couchbase Server for session storage with ASP.NET Core.
You will learn how to read, write session data and query session data with N1QL for business insights.

===== {empty}

====== Components
* Server 6.0

====== Languages
* C#
* ASP.NET
* ASP.NET Core

[.metadata]
=== Intermediate

[.developer]
== Mobile Developer

[.title]
=== xref:standalone@userprofile-couchbase-mobile:userprofile:userprofile_basic.adoc[User Profile Sample]

[.content]

[.summary]
The series of tutorials demonstrate the core functionality of Couchbase Mobile 2.x using an iOS app. 
The "Standalone" tutorial demonstrates the use of Couchbase Lite as a standalone, embedded data store and the fundamentals of Database Operations and CRUD. 
The "Query" tutorial extends the "Standalone" tutorial and demonstrates querying capabilities within Couchbase Lite.
The "Sync" tutorial demonstrates use of Couchbase Sync Gateway for data sync between Couchbase Lite clients
[.links]
xref:standalone@userprofile-couchbase-mobile:userprofile:userprofile_basic.adoc[Standalone]
xref:query@userprofile-couchbase-mobile:userprofile:userprofile_query.adoc[Query]
xref:sync@userprofile-couchbase-mobile:userprofile:userprofile_sync.adoc[Sync]

===== {empty}

====== Components
* Server 5.5
* Lite 2.1
* Sync Gateway 2.1

====== Languages
* Swift

[.metadata]
=== Beginner

[.developer]
== Mobile Developer

[.title]
=== Building a Cordova Plugin

==== {empty}
[.summary]
In this tutorial, you will learn how to use Couchbase Lite in a Cordova plugin for an Ionic project targeting iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.
[.links]
xref:tutorials:hotel-lister:ios.adoc[Swift]
xref:tutorials:hotel-lister:android.adoc[Java]

===== {empty}

====== Components
* Couchbase Lite 2.1

====== Languages
* Swift
* Java

[.metadata]
=== Beginner

[.developer]
== Mobile Developer

[.title]
=== Building a React Native Module

==== {empty}
[.summary]
In this tutorial, you will learn how to use Couchbase Lite in a React Native project for iOS and Android.
The user Interface is written in JavaScript while the business logic and data model is written in native Swift/Java.
[.links]
xref:tutorials:hotel-finder:ios.adoc[Swift]
xref:tutorials:hotel-finder:android.adoc[Java]

===== {empty}

====== Components
* Server 6.0

====== Languages
* N/A

[.metadata]
=== Beginner

[.developer]
== Mobile Developer

[.title]
=== xref:tutorials:todo-app:introduction.adoc[ToDo App]

==== {empty}
[.summary]
This simple ToDo List application is built with Couchbase Lite 2.0 for iOS, Android, UWP and Xamarin (iOS, Android) platforms.
Users can authenticate, create lists with tasks.
Each task can have an optional blob (image) attached to it.
Lists can be shared with multiple users.
[.links]
xref:tutorials:todo-app:develop/swift/create-database.adoc[Swift]
xref:tutorials:todo-app:develop/java/create-database.adoc[Java]

===== {empty}

====== Components
* Sync Gateway 1.5
* Couchbase Lite 1.4

====== Languages
* Swift
* Java

[.metadata]
=== Beginner

[.developer]
== Mobile Developer

[.title]
=== xref:tutorials:university-lister:android.adoc[Recycler Views with Live Queries]

==== {empty}
[.summary]
This tutorial will demonstrate how you can use Couchbase Lite as a data source for Recycler Views in your Android application.

===== {empty}

====== Components
* Couchbase Lite 2.1

====== Languages
* Java

[.metadata]
=== Beginner
